services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      - name=value
    volumes:
    - db_data:/var/lib/postgresql/data

  app:
    build:
      context: contextPath
      dockerfile: Dockerfile

volumes:
  db_data: