[project]
name = "crypto-price-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project.scripts]
price-tracker = "main:main"

[tool.setuptools]
py-modules = ["main"]
packages = ["app"]
